services:
  mountain-giants-app:
    container_name: mountain_giants
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    restart: always
    ports:
      - "3018:3018"
    environment:
      - NODE_ENV=production
      - PORT=3018
    # VOLUMES : Activer pour sauvegarder la base de données et les uploads !
    volumes:
      - ../backend/uploads:/app/backend/uploads
      - ../backend/data:/app/backend/data
      
    # CONFIGURATION TRAEFIK (HTTPS) - À décommenter quand vous aurez un nom de domaine
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.mountain-giants.rule=Host(`admin.votre-domaine.com`)"
    #   - "traefik.http.routers.mountain-giants.entrypoints=websecure"
    #   - "traefik.http.routers.mountain-giants.tls.certresolver=letsencrypt"
    #   - "traefik.http.services.mountain-giants.loadbalancer.server.port=3018"
